/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Util.DBConnect;
import Model.NhanVien;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author admin
 */
public class ImportExcelNhanVienView extends javax.swing.JDialog {

    /**
     * Creates new form ImportExcelNhanVienView
     */
    public ImportExcelNhanVienView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    DefaultTableModel dtm;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblExcel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Giới tính", "Ngày sinh", "Địa chỉ", "Sđt", "Chức Vụ", "Trạng thái", "Lương", "Tên TK", "Mật khẩu"
            }
        ));
        tblExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExcelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblExcel);

        jButton1.setText("Import Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addGap(119, 119, 119)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExcelMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblExcelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dtm = (DefaultTableModel) tblExcel.getModel();
        dtm.setRowCount(0);
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelImportWorkBook = null;
        String currentDirectoryPath = "C:\\Users\\admin\\Documents";
        JFileChooser ejfc = new JFileChooser(currentDirectoryPath);
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("Excel file", "xls", "xlsx", "xslm");
        ejfc.setFileFilter(extensionFilter);
        int excelchooser = ejfc.showOpenDialog(null);
        if (excelchooser == JFileChooser.APPROVE_OPTION) {
            try {
                File excelFile = ejfc.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelImportWorkBook = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelImportWorkBook.getSheetAt(0);
                for (int i = 1; i < excelSheet.getLastRowNum(); i++) {
                    XSSFRow excelRow = excelSheet.getRow(i);
                    XSSFCell maNV = excelRow.getCell(0);
                    XSSFCell ten = excelRow.getCell(1);
                    XSSFCell gioiTinh = excelRow.getCell(2);
                    String gioiTinhStr = String.valueOf(gioiTinh).equals("1") ? "Nam" : "Nữ";
//                    System.out.println("Gioi tinh sau khi convert string : " + gioiTinhStr);

//                    String gioiTinhStr = gioiTinh.equals("1")?"Nam":"Nữ";
                    java.util.Date ngaySinh = excelRow.getCell(3).getDateCellValue();
                    DateFormat dateFormatNgaySinh = new SimpleDateFormat("yyyy-MM-dd");
                    String strNgaySinh = dateFormatNgaySinh.format(ngaySinh);
//                  
                    XSSFCell SDT = excelRow.getCell(5);
                    XSSFCell diaChi = excelRow.getCell(4);
                    XSSFCell chucVu = excelRow.getCell(6);
//                    String chucVuString = String.valueOf(chucVu);
////                    Integer chucVuInt = Integer.parseInt(chucVuString);
//                    
//                    System.out.println("Chuc vu excel: " + chucVu);
                    String chucVuStr = String.valueOf(chucVu).equals("1") ? "1" : "0";
                    XSSFCell Luong = excelRow.getCell(8);
                    String luongStr = String.valueOf(chucVu);
                    XSSFCell tenTK = excelRow.getCell(9);
                    XSSFCell mk = excelRow.getCell(10);
                    XSSFCell trangThai = excelRow.getCell(7);
                    String trangThaiStr = String.valueOf(trangThai).equals("1") ? "1" : "0";

                    System.out.println();
                    dtm.addRow(new Object[]{maNV, ten, gioiTinhStr, strNgaySinh, diaChi, SDT, chucVuStr, trangThaiStr, Luong, tenTK, mk});
                }
                JOptionPane.showMessageDialog(rootPane, "Import Excel thanh cong");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                Logger.getLogger(ImportExcelNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Đây là phần thêm từ excelf db
        int insertedRows = 0;
        int row = tblExcel.getRowCount();
        String query = "INSERT INTO [dbo].[nhan_vien]\n"
                + "           ([maNhanVien]\n"
                + "           ,[tenNhanVien]\n"
                + "           ,[gioiTinh]\n"
                + "           ,[ngaySinh]\n"
                + "           ,[diachi]\n"
                + "           ,[sdt]\n"
                + "           ,[chucVu]\n"
                + "           ,[trangThai]\n"
                + "           ,[luong]\n"
                + "           ,[tenTaiKhoan]\n"
                + "           ,[matKhau])\n"
                + "     VALUES\n"
                + "           (?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement ps = null;
        Connection con = null;
        try {
            con = DBConnect.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ImportExcelNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < row; i++) {
            String maNV = dtm.getValueAt(i, 0).toString();
            String ten = dtm.getValueAt(i, 1).toString();
            String gioiTinh = dtm.getValueAt(i, 2).toString();
            String ngaySinh = dtm.getValueAt(i, 3).toString();
            String diachi = dtm.getValueAt(i, 4).toString();
            String SDT = dtm.getValueAt(i, 5).toString();

            
            String chucVu = dtm.getValueAt(i, 6).toString();
             String trangThai = dtm.getValueAt(i, 7).toString();
            String luong = dtm.getValueAt(i, 8).toString();
            String tenTK = dtm.getValueAt(i, 9).toString();
            String mk = dtm.getValueAt(i, 10).toString();
           

            try {
                ps = con.prepareStatement(query);
                ps.setString(1, maNV);
                ps.setString(2, ten);
                // gioiTinh - bit 
                // ngaySinh - date 
                Boolean gioiTinhBoolean = gioiTinh.equals("Nam") ? true : false;
                ps.setBoolean(3, gioiTinhBoolean);

//                    
//                    java.util.Date dateNgaySinhUtil = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(ngaySinh);
//                    java.sql.Date sqlDateNgaySinh = new java.sql.Date(dateNgaySinhUtil.getTime());
//                    ps.setDate(4, sqlDateNgaySinh);
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date parse = dateFormat.parse(ngaySinh);
                java.sql.Date sqlDate = new java.sql.Date(parse.getTime());

                ps.setDate(4, sqlDate);

//                String ngaySinh = txtNgaySinh.getText();
//                Date dateNgaySinh;
//                try {
//                    dateNgaySinh = new SimpleDateFormat("yyyy-mm-dd").parse(ngaySinh);
//                } catch (ParseException ex) {
//                    JOptionPane.showMessageDialog(this, "Bạn cần nhập ngày bắt đầu theo định dạng Year/Month/Day");
//                    return;
//                }
                ps.setString(5, diachi);
                ps.setString(6, SDT);
//                ps.setInt(6, Integer.valueOf(SDT));
                ps.setInt(7, Integer.parseInt(chucVu));   // kiểu int 
                ps.setFloat(9, Float.valueOf(luong));
                ps.setString(10, tenTK);
                ps.setString(11, mk);
                ps.setInt(8, Integer.parseInt(trangThai));

                int result = ps.executeUpdate();
                if (result > 0) {
                    insertedRows++;

                }

            } catch (Exception e) {
                e.printStackTrace(System.out);
            }
        }
        JOptionPane.showMessageDialog(null, " Du lieu da duoc them");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportExcelNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportExcelNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportExcelNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportExcelNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportExcelNhanVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExcel;
    // End of variables declaration//GEN-END:variables
}
